### ISSUE TITLE
Error in Dockerfile section - Python...

### ISSUE THREAD

**Issue by coforfe** [rstudio/vetiver.rstudio.com#52]
Hi,

I got a constant error when using:

```python
vetiver.write_docker(app_file)
```
The error says _"name 'vetiver' is not defined"_

but it worked by doing this:

```python
from vetiver import write_docker
write_docker(app_file)
```

Please could you check if this is fine?

Thanks,
Carlos.

**Comment by isabelizimm** [comment]
Hi Carlos, 

Thanks for the feedback! When you are getting this error, how have you imported vetiver? This sounds like it could be an issue with namespaces. For example, if you were to run:

```python
from vetiver import VetiverModel

vetiver.write_docker()
```

the error `NameError: name 'vetiver' is not defined` is expected, since your environment will only have VetiverModel, not all the vetiver functions. But, if you run something like

```python
import vetiver

vetiver.write_docker()
```
it should run as expected since all of vetiver would be imported.

**Comment by coforfe** [comment]
Hi Isabel,

OK.  Thanks!.
Yes it works fine!.

**Comment by isabelizimm** [comment]
Awesome, glad to help!
